In [ ]:
%pip install numpy scipy

## 1. Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [2]:
import numpy as np
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[2, 3, 3],
       [1, 1, 4],
       [5, 4, 5]])

## 2. Обчислити визначник матриці

In [3]:
det = np.linalg.det(matrix)
det

np.float64(19.999999999999996)

## 3. Знайти добуток всіх елементів матриці

In [4]:
product = np.prod(matrix)
product

np.int64(7200)

In [5]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(7200)

## 4. Знайти суму всіх елементів матриці

In [6]:
sum = np.sum(matrix)
sum

np.int64(28)

## 5. Обчислити найбільший, найменший елементи

In [7]:
max_element = np.max(matrix)
max_element

np.int64(5)

In [8]:
min_element = np.min(matrix)
min_element

np.int64(1)

## 6. Знайти середнє значення елементів матриці

In [9]:
mean = np.mean(matrix)
mean

np.float64(3.111111111111111)

## 7. Знайти матрицю, що складена з квадратних коренів.

In [10]:
sqrt_matrix = np.sqrt(matrix)
sqrt_matrix

array([[1.41421356, 1.73205081, 1.73205081],
       [1.        , 1.        , 2.        ],
       [2.23606798, 2.        , 2.23606798]])

## 8. Обчислити суму елементів кожного рядка. Відповідь записати  як вектор-стовпчик

In [11]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
row_sums

array([[ 8],
       [ 6],
       [14]])

## 9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [12]:
vector = np.random.randint(0, 10, size=25)
vector

array([0, 0, 5, 9, 8, 6, 8, 4, 8, 7, 1, 7, 5, 5, 1, 9, 7, 6, 3, 9, 1, 2,
       6, 7, 8])

In [13]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 9, 8, 8, 8, 8, 7, 7, 7, 7, 6, 6, 6, 5, 5, 5, 4, 3, 2, 1, 1,
       1, 0, 0])

## 10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [14]:
from scipy import stats
mode = stats.mode(vector)
mode

ModeResult(mode=np.int64(7), count=np.int64(4))

In [15]:
median = np.median(vector)
median

np.float64(6.0)

In [16]:
mean = np.mean(vector)
mean

np.float64(5.28)

In [17]:
max_value = np.max(vector)
max_value

np.int64(9)

In [18]:
min_value = np.min(vector)
min_value

np.int64(0)

## 11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [19]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix1

array([[ 4,  6,  3,  1],
       [ 3, 10,  8,  1],
       [ 7,  2,  2,  4],
       [ 1,  7,  1,  9]])

In [20]:
matrix2 = np.random.randint(1, 11, size=(4, 4))
matrix2

array([[ 8,  9,  6,  7],
       [ 2,  9,  5,  8],
       [ 8,  7,  1,  6],
       [10,  2,  8,  2]])

In [21]:
matrix_sum = matrix1 + matrix2
matrix_sum

array([[12, 15,  9,  8],
       [ 5, 19, 13,  9],
       [15,  9,  3, 10],
       [11,  9,  9, 11]])

In [22]:
matrix_diff = matrix1 - matrix2
matrix_diff

array([[-4, -3, -3, -6],
       [ 1,  1,  3, -7],
       [-1, -5,  1, -2],
       [-9,  5, -7,  7]])

In [23]:
matrix_product = matrix1 * matrix2
matrix_product

array([[32, 54, 18,  7],
       [ 6, 90, 40,  8],
       [56, 14,  2, 24],
       [10, 14,  8, 18]])

In [24]:
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))
matrix_division

array([[0.5       , 0.66666667, 0.5       , 0.14285714],
       [1.5       , 1.11111111, 1.6       , 0.125     ],
       [0.875     , 0.28571429, 2.        , 0.66666667],
       [0.1       , 3.5       , 0.125     , 4.5       ]])

## 12. Задати вектор-рядок, що містить дійсні числа 1.0-8.0. Зробити матрицю 3*3.Помножити на вектор-рядок, що містить числа 1.0-2.0

In [25]:
vec1 = np.arange(9.0)
vec1

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [26]:
vec1_matrix = vec1.reshape((3, 3))
vec1_matrix

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [27]:
vec2 = np.arange(3.0)
vec2

array([0., 1., 2.])

In [28]:
vec_multiply = np.multiply(vec1_matrix, vec2)
vec_multiply

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

## 13. Задати вектор-рядок (числа 1-5). Обчислити вектор в кубі.

In [29]:
vec3 = np.arange(6)
vec3

array([0, 1, 2, 3, 4, 5])

In [30]:
vec3_power = np.power(vec3, 3)
vec3_power

array([  0,   1,   8,  27,  64, 125])

## 14. Піднести до ступеня

In [31]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])